openapi: 3.0.1
info:
  title: Main Openapi Yaml
  version: 0.1.0
servers:
  - url: http://{server}:{port}/
    variables:
      server:
        default: localhost
      port:
        default: '9090'
paths:
  /enrich:
    get:
      operationId: getEnrich
      parameters:
        - name: emails
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnrichedUsersResponse'
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
        '500':
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
components:
  schemas:
    EnrichedUser:
      required:
        - company
        - email
        - location
        - name
        - title
      type: object
      properties:
        email:
          type: string
        name:
          type: string
        company:
          type: string
        title:
          type: string
        location:
          type: string
    EnrichedUsersResponse:
      required:
        - users
      type: object
      properties:
        users:
          type: array
          items:
            $ref: '#/components/schemas/EnrichedUser'
    ErrorPayload:
      required:
        - message
        - method
        - path
        - reason
        - status
        - timestamp
      type: object
      properties:
        timestamp:
          type: string
        status:
          type: integer
          format: int64
        reason:
          type: string
        message:
          type: string
        path:
          type: string
        method:
          type: string
