openapi: 3.0.1
info:
  title: /
  version: 0.1.0
servers:
  - url: http://{server}:{port}
    variables:
      server:
        default: localhost
      port:
        default: '9090'
paths:
  /users:
    get:
      operationId: getUsers
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersResponse'
components:
  schemas:
    UsersResponse:
      required:
        - users
      type: object
      properties:
        users:
          type: array
          items:
            type: string
  securitySchemes:
    DevantApiKeyAuth:
      type: apiKey
      in: header
      name: Choreo-API-Key
      x-ballerina-name: choreoAPIKey
security:
  - DevantApiKeyAuth: []
